const std = @import("std");
const types = @import("types.zig");
const device_arrays = @import("device_arrays.zig");

const DeviceIdx = types.DeviceIdx;
const NetIdx = types.NetIdx;
const TerminalType = types.TerminalType;
const DeviceType = types.DeviceType;
const DeviceParams = types.DeviceParams;
const DeviceArrays = device_arrays.DeviceArrays;

pub const PinEdgeArrays = struct {
    device: []DeviceIdx,
    net: []NetIdx,
    terminal: []TerminalType,
    position: [][2]f32,
    allocator: std.mem.Allocator,
    len: u32,

    pub fn init(allocator: std.mem.Allocator, count: u32) !PinEdgeArrays {
        const n: usize = @intCast(count);

        const devs = try allocator.alloc(DeviceIdx, n);
        errdefer allocator.free(devs);
        @memset(devs, DeviceIdx.fromInt(0));

        const nets = try allocator.alloc(NetIdx, n);
        errdefer allocator.free(nets);
        @memset(nets, NetIdx.fromInt(0));

        const terms = try allocator.alloc(TerminalType, n);
        errdefer allocator.free(terms);
        @memset(terms, .gate);

        const pos = try allocator.alloc([2]f32, n);
        errdefer allocator.free(pos);
        @memset(pos, .{ 0.0, 0.0 });

        return PinEdgeArrays{
            .device = devs,
            .net = nets,
            .terminal = terms,
            .position = pos,
            .allocator = allocator,
            .len = count,
        };
    }

    pub fn deinit(self: *PinEdgeArrays) void {
        self.allocator.free(self.device);
        self.allocator.free(self.net);
        self.allocator.free(self.terminal);
        self.allocator.free(self.position);
        self.* = undefined;
    }

    /// Compute pin offsets from device geometry so that each terminal has a
    /// distinct spatial position relative to the device origin (bottom-left
    /// of the gate channel in GDSII coordinates).
    ///
    /// These offsets must match the physical contact positions generated by
    /// `writeMosfetGeometry` / `writeMosfetGeometryFingered` in gdsii.zig so
    /// that the router targets the correct locations.
    ///
    /// For single-finger MOSFETs (nmos/pmos):
    ///   - source: (w/2, -0.13)         — S/D contact centre below gate
    ///   - drain:  (w/2, l + 0.13)      — S/D contact centre above gate
    ///   - gate:   (-0.20, l/2)         — gate contact pad left of channel
    ///   - body:   (w/2, -0.70)         — body tap below source
    ///
    /// For multi-finger MOSFETs (fingers > 1), contacts follow the fingered
    /// stack geometry from `writeMosfetGeometryFingered`:
    ///   contact_cy(region) = y - sd_ext/2 + region * (l + sd_ext)
    ///   - source (region=0):   offset_y = -sd_contact_y              (same)
    ///   - drain  (region=nf):  offset_y = nf*(l_scaled+sd_ext_um) - sd_contact_y
    ///   - gate:   y-center of gate bus = ((nf-1)*(l+sd_ext) + l) / 2
    ///   - body:   same formula as single-finger (diff_y_min = y - sd_ext always)
    ///
    /// For two-terminal devices (res/cap/ind):
    ///   - anode:   left  (-half_dim, 0)
    ///   - cathode: right (+half_dim, 0)
    ///
    /// When device dimensions are zero a small default (1.0) is used so that
    /// terminals still receive non-degenerate offsets.
    pub fn computePinOffsets(self: *PinEdgeArrays, devices: *const DeviceArrays) void {
        const n: usize = @intCast(self.len);

        // Minimum dimension so offsets are non-zero even when w/l are unset.
        const default_dim: f32 = 1.0;

        // Gate contact x-offset: gate_pad_width/2 * db_unit = 400/2 * 0.001 = 0.20 µm.
        // Constant — does not depend on channel length.
        const gate_contact_x: f32 = 0.20;

        for (0..n) |i| {
            const dev_raw: u32 = self.device[i].toInt();
            if (dev_raw >= devices.len) continue;

            const dev_type = devices.types[dev_raw];
            const params = devices.params[dev_raw];

            switch (dev_type) {
                .nmos, .pmos => {
                    const w = if (params.w > 0.0) params.w else default_dim;
                    const l = if (params.l > 0.0) params.l else default_dim;

                    // Scale to microns if values are in SI (< 1e-3).
                    // This keeps offsets in a reasonable placement-unit range.
                    const w_base = if (w < 1e-3) w * 1e6 else w;
                    const l_scaled = if (l < 1e-3) l * 1e6 else l;

                    // Apply multiplier (SPICE `m` parameter) to the width so
                    // that pin offsets match the effective gate width drawn by
                    // the GDSII writer (which also scales W by mult).
                    const mult: f32 = @floatFromInt(@max(@as(u16, 1), params.mult));
                    const w_scaled = w_base * mult;

                    // Finger count — must be at least 1.
                    const nf: f32 = @floatFromInt(@max(@as(u16, 1), params.fingers));

                    // For multi-finger devices the S/D stack pitch is
                    // (l + sd_ext) per finger.  Contact positions follow
                    // writeMosfetGeometryFingered in gdsii.zig:
                    //   contact_cy(region) = y - sd_ext/2 + region*(l+sd_ext)
                    // Offset from device origin y:
                    //   source (region 0):  -sd_ext/2          = -sd_contact_y
                    //   drain  (region nf): nf*(l+sd_ext) - sd_ext/2
                    //                     = nf*(l_scaled+sd_ext_um) - sd_contact_y
                    // Gate bus centre (from gdsii.zig gate_cy derivation):
                    //   = ((nf-1)*(l+sd_ext) + l) / 2
                    // Effective sd_extension matching effectiveSdExtension(l) in gdsii.zig:
                    //   raw = max(sd_ext_base, 2*(licon_half + m1_pad_enc) + m1_min_spacing - l)
                    //       = max(0.26, 0.39 - l_scaled)
                    // Rounded to nearest 0.002 µm (even db_unit) as in gdsii.zig.
                    const raw_sd: f32 = @max(0.26, 0.39 - l_scaled);
                    const eff_sd_ext_um: f32 = @ceil(raw_sd / 0.002) * 0.002;
                    const sd_contact_y: f32 = eff_sd_ext_um * 0.5;
                    const body_tap_y: f32 = eff_sd_ext_um + 0.44;

                    const drain_y = nf * (l_scaled + eff_sd_ext_um) - sd_contact_y;
                    const gate_y = ((nf - 1.0) * (l_scaled + eff_sd_ext_um) + l_scaled) * 0.5;

                    self.position[i] = switch (self.terminal[i]) {
                        .gate => .{ -gate_contact_x, gate_y },
                        .source => .{ w_scaled * 0.5, -sd_contact_y },
                        .drain => .{ w_scaled * 0.5, drain_y },
                        .body => .{ 0.0, -body_tap_y },
                        // Fallback for unexpected terminal types on a MOSFET.
                        .anode => .{ -w_scaled * 0.5, 0.0 },
                        .cathode => .{ w_scaled * 0.5, 0.0 },
                        .collector, .base, .emitter => .{ 0.0, 0.0 },
                    };
                },
                .res, .cap, .ind,
                .res_poly, .res_diff_n, .res_diff_p, .res_well_n, .res_well_p, .res_metal,
                .cap_mim, .cap_mom, .cap_pip, .cap_gate => {
                    // Two-terminal: use value or a default for spacing.
                    const dim = if (params.w > 0.0)
                        params.w
                    else if (params.l > 0.0)
                        params.l
                    else
                        default_dim;

                    const dim_scaled = if (dim < 1e-3) dim * 1e6 else dim;
                    const half = dim_scaled * 0.5;

                    self.position[i] = switch (self.terminal[i]) {
                        .anode => .{ -half, 0.0 },
                        .cathode => .{ half, 0.0 },
                        // Fallback for other terminal types.
                        else => .{ 0.0, 0.0 },
                    };
                },
                .subckt => {
                    // Subcircuit instances: spread ports along x-axis.
                    // Use a default spacing since subcircuits have no w/l.
                    const half = default_dim * 0.5;
                    self.position[i] = switch (self.terminal[i]) {
                        .anode, .source, .emitter => .{ -half, 0.0 },
                        .cathode, .drain, .collector => .{ half, 0.0 },
                        .gate, .base => .{ 0.0, 0.0 },
                        .body => .{ 0.0, -half },
                    };
                },
                .diode => {
                    const dim = if (params.w > 0.0) params.w else default_dim;
                    const dim_scaled = if (dim < 1e-3) dim * 1e6 else dim;
                    const half = dim_scaled * 0.5;
                    self.position[i] = switch (self.terminal[i]) {
                        .anode => .{ -half, 0.0 },
                        .cathode => .{ half, 0.0 },
                        else => .{ 0.0, 0.0 },
                    };
                },
                .bjt_npn, .bjt_pnp => {
                    const half = default_dim * 0.5;
                    self.position[i] = switch (self.terminal[i]) {
                        .collector => .{ 0.0, half },
                        .base => .{ -half, 0.0 },
                        .emitter => .{ 0.0, -half },
                        .body => .{ half, 0.0 },
                        else => .{ 0.0, 0.0 },
                    };
                },
                .jfet_n, .jfet_p => {
                    const half = default_dim * 0.5;
                    self.position[i] = switch (self.terminal[i]) {
                        .drain => .{ 0.0, half },
                        .gate => .{ -half, 0.0 },
                        .source => .{ 0.0, -half },
                        else => .{ 0.0, 0.0 },
                    };
                },
            }
        }
    }
};

// ─── Tests ───────────────────────────────────────────────────────────────────

test "PinEdgeArrays init and deinit" {
    var pa = try PinEdgeArrays.init(std.testing.allocator, 6);
    defer pa.deinit();

    try std.testing.expectEqual(@as(u32, 6), pa.len);
    try std.testing.expectEqual(@as(usize, 6), pa.device.len);
    try std.testing.expectEqual(DeviceIdx.fromInt(0), pa.device[0]);
    try std.testing.expectEqual(NetIdx.fromInt(0), pa.net[5]);
    try std.testing.expectEqual(TerminalType.gate, pa.terminal[3]);
    try std.testing.expectEqual(@as(f32, 0.0), pa.position[2][1]);
}

test "PinEdgeArrays zero-count" {
    var pa = try PinEdgeArrays.init(std.testing.allocator, 0);
    defer pa.deinit();

    try std.testing.expectEqual(@as(u32, 0), pa.len);
}

test "PinEdgeArrays init with count=100 all slices correct length" {
    var pa = try PinEdgeArrays.init(std.testing.allocator, 100);
    defer pa.deinit();

    try std.testing.expectEqual(@as(u32, 100), pa.len);
    try std.testing.expectEqual(@as(usize, 100), pa.device.len);
    try std.testing.expectEqual(@as(usize, 100), pa.net.len);
    try std.testing.expectEqual(@as(usize, 100), pa.terminal.len);
    try std.testing.expectEqual(@as(usize, 100), pa.position.len);
}

test "PinEdgeArrays terminal types default to gate" {
    var pa = try PinEdgeArrays.init(std.testing.allocator, 20);
    defer pa.deinit();

    for (pa.terminal) |t| {
        try std.testing.expectEqual(TerminalType.gate, t);
    }
}

test "PinEdgeArrays device defaults to DeviceIdx(0)" {
    var pa = try PinEdgeArrays.init(std.testing.allocator, 10);
    defer pa.deinit();

    for (pa.device) |d| {
        try std.testing.expectEqual(DeviceIdx.fromInt(0), d);
    }
}

test "PinEdgeArrays net defaults to NetIdx(0)" {
    var pa = try PinEdgeArrays.init(std.testing.allocator, 10);
    defer pa.deinit();

    for (pa.net) |n| {
        try std.testing.expectEqual(NetIdx.fromInt(0), n);
    }
}

test "PinEdgeArrays position defaults to (0,0)" {
    var pa = try PinEdgeArrays.init(std.testing.allocator, 10);
    defer pa.deinit();

    for (pa.position) |pos| {
        try std.testing.expectEqual(@as(f32, 0.0), pos[0]);
        try std.testing.expectEqual(@as(f32, 0.0), pos[1]);
    }
}

test "PinEdgeArrays mutate all terminal types" {
    var pa = try PinEdgeArrays.init(std.testing.allocator, 6);
    defer pa.deinit();

    pa.terminal[0] = .gate;
    pa.terminal[1] = .drain;
    pa.terminal[2] = .source;
    pa.terminal[3] = .body;
    pa.terminal[4] = .anode;
    pa.terminal[5] = .cathode;

    try std.testing.expectEqual(TerminalType.gate, pa.terminal[0]);
    try std.testing.expectEqual(TerminalType.drain, pa.terminal[1]);
    try std.testing.expectEqual(TerminalType.source, pa.terminal[2]);
    try std.testing.expectEqual(TerminalType.body, pa.terminal[3]);
    try std.testing.expectEqual(TerminalType.anode, pa.terminal[4]);
    try std.testing.expectEqual(TerminalType.cathode, pa.terminal[5]);
}

test "computePinOffsets MOSFET with SI dimensions" {
    // Simulate a single NMOS with w=2u, l=0.18u and 4 pins (gate, drain, source, body).
    var pa = try PinEdgeArrays.init(std.testing.allocator, 4);
    defer pa.deinit();

    var da = try DeviceArrays.init(std.testing.allocator, 1);
    defer da.deinit();

    da.types[0] = .nmos;
    da.params[0] = .{ .w = 2e-6, .l = 0.18e-6, .fingers = 1, .mult = 1, .value = 0.0 };

    // All pins belong to device 0.
    pa.device[0] = DeviceIdx.fromInt(0);
    pa.device[1] = DeviceIdx.fromInt(0);
    pa.device[2] = DeviceIdx.fromInt(0);
    pa.device[3] = DeviceIdx.fromInt(0);

    pa.terminal[0] = .gate;
    pa.terminal[1] = .drain;
    pa.terminal[2] = .source;
    pa.terminal[3] = .body;

    pa.computePinOffsets(&da);

    // w=2u -> scaled to 2.0, l=0.18u -> scaled to 0.18
    // Offsets match physical contact positions from gdsii.zig:
    //   gate:   (-0.20, l/2) = (-0.20, 0.09)
    //   drain:  (w/2, l+0.13) = (1.0, 0.31)
    //   source: (w/2, -0.13) = (1.0, -0.13)
    //   body:   (w/2, -0.70) = (1.0, -0.70)

    // gate at (-0.20, l_scaled/2)
    try std.testing.expectApproxEqAbs(@as(f32, -0.20), pa.position[0][0], 1e-6);
    try std.testing.expectApproxEqAbs(@as(f32, 0.09), pa.position[0][1], 1e-6);

    // drain at (w/2, l+0.13)
    try std.testing.expectApproxEqAbs(@as(f32, 1.0), pa.position[1][0], 1e-6);
    try std.testing.expectApproxEqAbs(@as(f32, 0.31), pa.position[1][1], 1e-6);

    // source at (w/2, -0.13)
    try std.testing.expectApproxEqAbs(@as(f32, 1.0), pa.position[2][0], 1e-6);
    try std.testing.expectApproxEqAbs(@as(f32, -0.13), pa.position[2][1], 1e-6);

    // body at (0, -0.70) — x_tap = x (left edge of device)
    try std.testing.expectApproxEqAbs(@as(f32, 0.0), pa.position[3][0], 1e-6);
    try std.testing.expectApproxEqAbs(@as(f32, -0.70), pa.position[3][1], 1e-6);
}

test "computePinOffsets resistor two-terminal" {
    var pa = try PinEdgeArrays.init(std.testing.allocator, 2);
    defer pa.deinit();

    var da = try DeviceArrays.init(std.testing.allocator, 1);
    defer da.deinit();

    da.types[0] = .res;
    da.params[0] = .{ .w = 0.0, .l = 0.0, .fingers = 1, .mult = 1, .value = 10e3 };

    pa.device[0] = DeviceIdx.fromInt(0);
    pa.device[1] = DeviceIdx.fromInt(0);
    pa.terminal[0] = .anode;
    pa.terminal[1] = .cathode;

    pa.computePinOffsets(&da);

    // w=0, l=0 -> falls back to default_dim=1.0, half=0.5
    try std.testing.expectApproxEqAbs(@as(f32, -0.5), pa.position[0][0], 1e-6);
    try std.testing.expectApproxEqAbs(@as(f32, 0.5), pa.position[1][0], 1e-6);
}

test "computePinOffsets zero-dimensional MOSFET uses default" {
    var pa = try PinEdgeArrays.init(std.testing.allocator, 2);
    defer pa.deinit();

    var da = try DeviceArrays.init(std.testing.allocator, 1);
    defer da.deinit();

    da.types[0] = .pmos;
    // w=0, l=0 -> defaults kick in

    pa.device[0] = DeviceIdx.fromInt(0);
    pa.device[1] = DeviceIdx.fromInt(0);
    pa.terminal[0] = .source;
    pa.terminal[1] = .drain;

    pa.computePinOffsets(&da);

    // default_dim=1.0, w_scaled=1.0, l_scaled=1.0
    // source at (w/2, -0.13) = (0.5, -0.13)
    // drain at (w/2, l+0.13) = (0.5, 1.13)
    try std.testing.expectApproxEqAbs(@as(f32, 0.5), pa.position[0][0], 1e-6);
    try std.testing.expectApproxEqAbs(@as(f32, -0.13), pa.position[0][1], 1e-6);
    try std.testing.expectApproxEqAbs(@as(f32, 0.5), pa.position[1][0], 1e-6);
    try std.testing.expectApproxEqAbs(@as(f32, 1.13), pa.position[1][1], 1e-6);
    // Source and drain should be at distinct positions.
    try std.testing.expect(pa.position[0][1] != pa.position[1][1]);
}
